In [1]:
#importing packages
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
#loading data
df = pd.read_csv("Datasets/area_vs_price.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
#create an instance of regression model(class object) and fit the input data
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
#prediction using trained model
model.predict([[5000]])

array([859554.79452055])

# Save Model To a File Using Python Pickle

In [7]:
import pickle

In [8]:
with open('model_pickle','wb') as file:    # opens a file in write binary mode
    pickle.dump(model,file)                # save the Trained LinearRegression model to the file
                                           # saved file consists of binary keywords

## Load Saved Model

In [9]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)                 # open the saved file and load the trained model to an object named mp
                                           # now, model can be assessed using name mp

In [10]:
mp.coef_

array([135.78767123])

In [11]:
mp.intercept_

180616.43835616432

In [12]:
mp.predict([[5000]])

array([859554.79452055])

# Save Model To a File Using Joblib

In [13]:
import joblib

In [14]:
joblib.dump(model, 'model_joblib')    # save the Trained LinearRegression model to the file
                                      # saved file consists of binary keywords

['model_joblib']

In [15]:
mj = joblib.load('model_joblib')      # open the saved file and load the trained model to an object named mj
                                      # now, model can be assessed using name mj

In [16]:
mj.coef_

array([135.78767123])

In [17]:
mj.intercept_

180616.43835616432

In [18]:
mj.predict([[5000]])

array([859554.79452055])