# Implementation of SVM on digits dataset

In [1]:
import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.JPIJNSWNNAN3CE6LLI5FWSPHUT2VXMTH.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [4]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# digits.data provies 2-D array representation of the image ( 64*64pixels )
df = pd.DataFrame(digits.data)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [6]:
df['target'] = digits.target
df.head(20)

0    1     2     3     4     5     6    7    8     9  ...   55   56  \
0   0.0  0.0   5.0  13.0   9.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
1   0.0  0.0   0.0  12.0  13.0   5.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
2   0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
3   0.0  0.0   7.0  15.0  13.0   1.0   0.0  0.0  0.0   8.0  ...  0.0  0.0   
4   0.0  0.0   0.0   1.0  11.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
5   0.0  0.0  12.0  10.0   0.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
6   0.0  0.0   0.0  12.0  13.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
7   0.0  0.0   7.0   8.0  13.0  16.0  15.0  1.0  0.0   0.0  ...  0.0  0.0   
8   0.0  0.0   9.0  14.0   8.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
9   0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  0.0   2.0  ...  0.0  0.0   
10  0.0  0.0   1.0   9.0  15.0  11.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
11  0.0  0.0   0.0   0.0  14.0  13.0   1.0  0.0  0.0   0.0  ...  0.0  0.0   
12  0.0  0.0   5.0  12.0   1.0   0.0   0.0  0.0  0.0   0.0  ...  2.0  0.0   
13  0.0  2.0   9.0  15.0  14.0   9.0   3.0  0.0  0.0   4.0  ...  0.0  0.0   
14  0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
15  0.0  5.0  12.0  13.0  16.0  16.0   2.0  0.0  0.0  11.0  ...  0.0  0.0   
16  0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0  ...  2.0  0.0   
17  0.0  0.0   1.0   8.0  15.0  10.0   0.0  0.0  0.0   3.0  ...  0.0  0.0   
18  0.0  0.0  10.0   7.0  13.0   9.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
19  0.0  0.0   6.0  14.0   4.0   0.0   0.0  0.0  0.0   0.0  ...  2.0  0.0   

     57    58    59    60    61    62   63  target  
0   0.0   6.0  13.0  10.0   0.0   0.0  0.0       0  
1   0.0   0.0  11.0  16.0  10.0   0.0  0.0       1  
2   0.0   0.0   3.0  11.0  16.0   9.0  0.0       2  
3   0.0   7.0  13.0  13.0   9.0   0.0  0.0       3  
4   0.0   0.0   2.0  16.0   4.0   0.0  0.0       4  
5   0.0   9.0  16.0  16.0  10.0   0.0  0.0       5  
6   0.0   1.0   9.0  15.0  11.0   3.0  0.0       6  
7   0.0  13.0   5.0   0.0   0.0   0.0  0.0       7  
8   0.0  11.0  16.0  15.0  11.0   1.0  0.0       8  
9   0.0   9.0  12.0  13.0   3.0   0.0  0.0       9  
10  0.0   1.0  10.0  13.0   3.0   0.0  0.0       0  
11  0.0   0.0   1.0  13.0  16.0   1.0  0.0       1  
12  0.0   3.0  11.0   8.0  13.0  12.0  4.0       2  
13  2.0  12.0  12.0  13.0  11.0   0.0  0.0       3  
14  0.0   0.0  10.0  15.0   4.0   0.0  0.0       4  
15  4.0  15.0  16.0   2.0   0.0   0.0  0.0       5  
16  0.0   0.0   7.0  15.0  16.0  11.0  0.0       6  
17  0.0   0.0  11.0   9.0   0.0   0.0  0.0       7  
18  0.0  11.0  14.0   5.0   0.0   0.0  0.0       8  
19  0.0   7.0  16.0  16.0  13.0  11.0  1.0       9  

[20 rows x 65 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('target',axis='columns'), df.target, test_size=0.3)

## Hyperparameter Tuning
### Using RBF Kernel

In [8]:
from sklearn.svm import SVC
rbf_model = SVC(kernel='rbf')

rbf_model.fit(X_train, y_train)

SVC()

In [9]:
rbf_model.predict(X_test)

array([1, 9, 0, 8, 0, 2, 1, 0, 0, 7, 3, 7, 1, 5, 3, 0, 5, 8, 0, 0, 9, 6,
       1, 3, 3, 9, 1, 9, 5, 6, 0, 3, 6, 3, 4, 0, 9, 8, 1, 4, 9, 3, 1, 0,
       1, 4, 3, 4, 6, 1, 6, 8, 1, 2, 5, 0, 4, 0, 3, 3, 9, 5, 3, 8, 3, 3,
       4, 2, 6, 1, 1, 3, 8, 1, 7, 1, 2, 2, 2, 3, 9, 0, 8, 2, 4, 1, 9, 8,
       2, 1, 7, 3, 1, 2, 8, 9, 4, 7, 5, 6, 1, 2, 2, 1, 2, 5, 4, 9, 6, 0,
       7, 2, 3, 3, 3, 4, 0, 5, 1, 5, 3, 4, 5, 8, 0, 3, 8, 1, 4, 9, 4, 8,
       3, 2, 6, 9, 1, 1, 2, 2, 2, 7, 5, 5, 6, 7, 2, 7, 0, 0, 4, 9, 5, 6,
       5, 3, 2, 8, 7, 7, 0, 3, 3, 4, 0, 4, 7, 1, 5, 7, 2, 7, 0, 9, 1, 1,
       5, 9, 2, 5, 9, 8, 4, 6, 7, 2, 5, 0, 4, 8, 3, 4, 3, 7, 5, 1, 7, 9,
       3, 2, 4, 8, 3, 7, 8, 7, 9, 0, 7, 1, 8, 9, 6, 7, 4, 3, 8, 8, 4, 1,
       8, 8, 8, 6, 9, 3, 7, 2, 8, 0, 5, 1, 6, 8, 3, 4, 0, 1, 7, 3, 0, 4,
       0, 0, 3, 4, 1, 5, 6, 8, 3, 6, 2, 7, 7, 4, 3, 3, 7, 3, 3, 6, 3, 2,
       2, 4, 4, 9, 6, 5, 4, 4, 6, 5, 6, 4, 2, 5, 6, 6, 2, 0, 6, 6, 8, 5,
       0, 0, 8, 7, 2, 7, 7, 8, 9, 5, 4, 0, 8, 7, 3,

In [10]:
rbf_model.score(X_test,y_test)

0.9833333333333333

### Using Linear kernel

In [11]:
linear_model = SVC(kernel='linear')
linear_model.fit(X_train,y_train)

SVC(kernel='linear')

In [12]:
linear_model.score(X_test,y_test)

0.9777777777777777

In [13]:
linear_model.score(X_test,y_test)

0.9777777777777777